if (MSVC)
   add_library(DspLib STATIC IMPORTED)
   set_target_properties(DspLib PROPERTIES IMPORTED_LOCATION "C:\\MyTools\\MyLib\\lib\\DspLib.lib")
   target_include_directories(DspLib INTERFACE "C:\\MyTools\\MyLib\\include\\DspLib")

   find_package(RisLib CONFIG REQUIRED PATHS ${MyRisLibConfigPath} NO_DEFAULT_PATH)
   get_target_property(_RisLib_interface_include RisLib INTERFACE_INCLUDE_DIRECTORIES)
   target_include_directories(DspLib INTERFACE ${_RisLib_interface_include})
   target_link_libraries(DspLib INTERFACE RisLib)
else()
   add_library(DspLib STATIC IMPORTED)
   set_target_properties(DspLib PROPERTIES IMPORTED_LOCATION "/usr/local/lib/libDspLib.a")
   target_include_directories(DspLib INTERFACE "/usr/local/include/DspLib")

   set(THREADS_PREFER_PTHREAD_FLAG ON)
   find_package(Threads REQUIRED)
   target_link_libraries(DspLib INTERFACE Threads::Threads)
endif()
